### ISSUE TITLE
bootstrap-datepicker css is out of date/incorrect

### ISSUE THREAD

**Issue by mthomps** [bootstrap-ruby/bootstrap-editable-rails#22]
The embedded datepicker css contains some 'top' & 'left' values on the .datepicker-dropdown:before and :after. These values don't exist in the current version of the standalone datepicker and cause a bug where the left column of dates is unclickable when it is oriented on top of an input. 

To fix, maybe the datepicker css should be updated, or it should be removed and a dependency added on the bootstrap-datepicker-rails gem.

**Comment by tkawa** [comment]
Thanks.
This gem is based on the build of X-editable for bootstrap 3. However, it seems to lack enough support of datepicker.
http://vitalets.github.io/x-editable/demo-bs3.html
So, I'm going to remove the part of datepicker from css, and you'll be able to use bootstrap-datepicker-rails gem put together.

**Comment by mthomps** [comment]
Thanks!

**Comment by tkawa** [comment]
I've released the new version of the gem! Enjoy!
